#include <stdint.h>

struct Connedted_Device
{
uint8_t mac[7];
uint16_t Conn_Handle;
uint16_t Handle_id;
uint8_t status;
uint8_t Central_ID[4];
char *Device_State; 
};

struct Connedted_Device Conn_Device_List[6];

struct BLE_Mode
{
	uint8_t BLE_state;
	char *BLE_Central_status;
	uint8_t BLE_Peripheral_status;
	uint8_t BLE_PC_Status;
	uint8_t Slave_Count;
	uint8_t Master_Count;
	char Scanned_Device_Flag;
};

struct BLE_Mode BLE_Mode_Change;



#define PKT_COMMAND	0x01
#define PKT_EVENT 0x04
#define APP_TX_PDU_SIZE	54	//27
#define APP_TX_TIME		656	//328
#define APP_RX_PDU_SIZE	54	//27
#define APP_RX_TIME		656	//328

#define NULL_BYTE	0x00
#define MAKE16OFXY(x, y)	((x << 8) | y)
#define LSBYTEOF16BIT(x)	(x & 0xFF)
#define MSBYTEOF16BIT(x)	((x >> 8) & 0xFF)

/*******************BT Commands**********************/
#define BT_DISCONNECT  				0x0406
#define BT_READ_REMOTE_VERSION_INFORMATION 	0x041D
#define BT_SET_EVENT_MASK 			0x0C01
#define BT_RESET    				0x0C03

#define GET_PARAM                                0xFE31



#define BT_READ_TRANSMIT_POWER_LEVEL		0x0C2D
#define BT_SET_CONTROLLER_TO_HOST_FLOW_CONTROL 	0x0C31
#define BT_HOST_BUFFER_SIZE			0x0C33
#define BT_HOST_NUMBER_OF_COMPLETED_PACKETS 	0x0C35
#define BT_SET_EVENT_MASK_PAGE 			0x0C63
#define BT_READ_AUTHENTICATED_PAYLOAD_TIMEOUT 	0x0C7B
#define BT_WRITE_AUTHENTICATED_PAYLOAD_TIMEOUT	0x0C7C
#define BT_READ_LOCAL_VERSION_INFORMATION 	0x1001
#define BT_READ_LOCAL_SUPPORTED_COMMANDS 	0x1002
#define BT_READ_LOCAL_SUPPORTED_FEATURES	0x1003
#define BT_READ_BD_ADDR 			0x1009
#define BT_READ_RSSI 				0x1405
/****************************************************/

#define LE_SET_EVENT_MASK	0x2001
#define LE_READ_BUFFER_SIZE	0x2002
#define LE_READ_LOCAL_SUPPORTED_FEATURES	0x2003
#define LE_SET_RANDOM_ADDRESS	0x2005
#define LE_SET_ADVERTISING_PARAMETERS	0x2006
#define LE_READ_ADVERTISING_CHANNEL_TX_POWER	0x2007
#define LE_SET_ADVERTISING_DATA		0x2008
#define LE_SET_SCAN_RESPONSE_DATA	0x2009
#define LE_SET_ADVERTISE_ENABLE		0x200A
#define LE_SET_SCAN_PARAMETERS	0x200B
#define LE_SET_SCAN_ENABLE	0x200C
#define LE_CREATE_CONNECTION	0x200D
#define LE_CREATE_CONNECTION_CANCEL		0x200E
#define LE_READ_WHITE_LIST_SIZE		0x200F
#define LE_CLEAR_WHITE_LIST		0x2010

#define LE_ADD_DEVICE_TO_WHITE_LIST	0x2011
#define LE_REMOVE_DEVICE_FROM_WHITE_LIST	0x2012
#define LE_CONNECTION_UPDATE	0x2013
#define LE_SET_HOST_CHANNEL_CLASSIFICATION	0x2014
#define LE_READ_CHANNEL_MAP		0x2015
#define LE_READ_REMOTE_USED_FEATURES	0x2016
#define LE_ENCRYPT	0x2017
#define LE_RAND		0x2018
#define LE_START_ENCRYPTION	0x2019
#define LE_LONG_TERM_KEY_REQUESTED_REPLY	0x201A
#define LE_LONG_TERM_KEY_REQUESTED_NEGATIVE_REPLY	0x201B

#define LE_READ_SUPPORTED_STATES	0x201C
#define LE_RECEIVER_TEST	0x201D
#define LE_TRANSMITTER_TEST		0x201E
#define LE_TEST_END_COMMAND		0x201F
#define LE_REMOTE_CONNECTION_PARAMETER_REQUEST_REPLY	0x2020
#define LE_REMOTE_CONNECTION_PARAMETER_REQUEST_NEGATIVE_REPLY	0x2021

//==============================================================================
//LE EVENTS

#define LE_CONNECTION_COMPLETE	0x3E	0x01
#define LE_ADVERTISING_REPORT	0x3E	0x02
#define LE_CONNECTION_UPDATE_COMPLETE	0x3E	0x03
#define LE_READ_REMOTE_USED_FEATURES_COMPLETE	0x3E	0x04
#define LE_LONG_TERM_KEY_REQUESTED	0x3E	0x05
#define LE_REMOTE_CONNECTION_PARAMETER_REQUEST	0x3E	0x06
//==============================================================================
//BT_EVENTS

#define BT_DISCONNECTION_COMPLETE	0x05
#define BT_ENCRYPTION_CHANGE	0x08
#define BT_READ_REMOTE_VERSION_INFORMATION_COMPLETE 	0x0C
#define BT_COMMAND_COMPLETE	 0x0E
#define BT_COMMAND_STATUS	0x0F
#define BT_HARDWARE_ERROR	0x10
#define BT_NUMBER_OF_COMPLETED_PACKETS	0x13
#define BT_DATA_BUFFER_OVERFLOW	 0x1A
#define BT_ENCRYPTION_KEY_REFRESH_COMPLETE	0x30
#define BT_AUTHENTICATED_PAYLOAD_TIMEOUT_EXPIRED	0x57

//==============================================================================
//VENDOR_SPECIFIC COMMANDS

#define VS_HCI_EXTENSION_SET_RX_GAIN	0xFC00
#define VS_HCI_EXTENSION_SET_TX_POWER	0xFC01
#define VS_HCI_EXTENSION_ONE_PACKET_PER_EVENT	0xFC02
#define VS_HCI_EXTENSION_CLOCK_DIVIDE_ON_HALT	0xFC03
#define VS_HCI_EXTENSION_DECLARE_NV_USAGE	0xFC04
#define VS_HCI_EXTENSION_DECRYPT	0xFC05
#define VS_HCI_EXTENSION_SET_LOCAL_SUPPORTED_FEATURES	0xFC06
#define VS_HCI_EXTENSION_SET_FAST_TX_RESPONSE_TIME	0xFC07
#define VS_HCI_EXTENSION_MODEM_TEST_TX	0xFC08

#define VS_HCI_EXTENSION_MODEM_HOP_TEST_TX	0xFC09
#define VS_HCI_EXTENSION_MODEM_TEST_RX	0xFC0A
#define VS_HCI_EXTENSION_END_MODEM_TEST	0xFC0B
#define VS_HCI_EXTENSION_SET_BDADDR	0xFC0C
#define VS_HCI_EXTENSION_SET_SCA	0xFC0D
#define VS_HCI_EXTENSION_ENABLE_PTM	0xFC0E
#define VS_HCI_EXTENSION_SET_FREQUENCY_TUNING	0xFC0F
#define VS_HCI_EXTENSION_SAVE_FREQUENCY_TUNING 0xFC10
#define VS_HCI_EXTENSION_SET_MAX_DTM_TX_POWER  0xFC11
#define VS_HCI_EXTENSION_MAP_PM_IO_PORT  0xFC12
#define VS_HCI_EXTENSION_DISCONNECT_IMMEDIATE  0xFC13
#define VS_HCI_EXTENSION_PACKET_ERROR_RATE 0xFC14
#define VS_HCI_EXTENSION_PACKET_ERROR_RATE_BY_CHANNEL  0xFC15
#define VS_HCI_EXTENSION_EXTEND_RF_RANGE 0xFC16
#define VS_HCI_EXTENSION_ADVERTISER_EVENT_NOTICE 0xFC17
#define VS_HCI_EXTENSION_CONNECTION_EVENT_NOTICE 0xFC18
#define VS_HCI_EXTENSION_HALT_DURING_RF  0xFC19
#define VS_HCI_EXTENSION_SET_SLAVE_LATENCY_OVERRIDE  0xFC1A
#define VS_HCI_EXTENSION_BUILD_REVISION  0xFC1B
#define VS_HCI_EXTENSION_DELAY_SLEEP 0xFC1C
#define VS_HCI_EXTENSION_RESET_SYSTEM  0xFC1D
#define VS_HCI_EXTENSION_OVERLAPPED_PROCESSING 0xFC1E
#define VS_HCI_EXTENSION_NUMBER_COMPLETED_PACKETS_LIMIT  0xFC1F
#define VS_HCI_EXTENSION_GET_CONNECTION_INFORMATION  0xFC20
#define VS_HCI_EXTENSION_SET_MAX_DATA_LENGTH	0xFC21
#define VS_L2CAP_DISCONNECTION_REQUEST 0xFC86
#define VS_L2CAP_CONNECTION_PARAMETER_UPDATE_REQUEST 0xFC92
#define VS_L2CAP_CONNECTION_REQUEST  0xFC94
#define VS_L2CAP_CONNECTION_RESPONSE 0xFC95
#define VS_L2CAP_FLOW_CONTROL_CREDIT 0xFC96
#define VS_L2CAP_DATA  0xFCF0
#define VS_L2CAP_REGISTER_PSM  0xFCF1
#define VS_L2CAP_DEREGISTER_PSM  0xFCF2
#define VS_L2CAP_PSM_INFO  0xFCF3
#define VS_L2CAP_PSM_CHANNELS  0xFCF4
#define VS_L2CAP_CHANNEL_INFO  0xFCF5

#define VS_ATT_ERROR_RESPONSE  0xFD01
#define VS_ATT_EXCHANGE_MTU_REQUEST  0xFD02
#define VS_ATT_EXCHANGE_MTU_RESPONSE 0xFD03
#define VS_ATT_FIND_INFORMATION_REQUEST  0xFD04
#define VS_ATT_FIND_INFORMATION_RESPONSE 0xFD05
#define VS_ATT_FIND_BY_TYPE_VALUE_REQUEST  0xFD06
#define VS_ATT_FIND_BY_TYPE_VALUE_RESPONSE 0xFD07
#define VS_ATT_READ_BY_TYPE_REQUEST  0xFD08
#define VS_ATT_READ_BY_TYPE_RESPONSE 0xFD09
#define VS_ATT_READ_REQUEST  0xFD0A
#define VS_ATT_READ_RESPONSE 0xFD0B
#define VS_ATT_READ_BLOB_REQUEST 0xFD0C
#define VS_ATT_READ_BLOB_RESPONSE  0xFD0D
#define VS_ATT_READ_MULTIPLE_REQUEST 0xFD0E
#define VS_ATT_READ_MULTIPLE_RESPONSE  0xFD0F
#define VS_ATT_READ_BY_GROUP_TYPE_REQUEST  0xFD10
#define VS_ATT_READ_BY_GROUP_TYPE_RESPONSE 0xFD11
#define VS_ATT_WRITE_REQUEST 0xFD12
#define VS_ATT_WRITE_RESPONSE  0xFD13
#define VS_ATT_PREPARE_WRITE_REQUEST 0xFD16
#define VS_ATT_PREPARE_WRITE_RESPONSE  0xFD17
#define VS_ATT_EXECUTE_WRITE_REQUEST	0xFD18
#define VS_ATT_EXECUTE_WRITE_RESPONSE	0xFD19
#define VS_ATT_HANDLE_VALUE_NOTIFICATION	0xFD1B
#define VS_ATT_HANDLE_VALUE_INDICATION	0xFD1D
#define VS_ATT_HANDLE_VALUE_CONFIRMATION	0xFD1E

#define VS_GATT_DISCOVER_CHARACTERISTICS_BY_UUID	0xFD88
#define VS_GATT_WRITE_LONG	0xFD96

#define VS_GAP_DEVICE_INITIALIZATION	0xFE00
#define VS_GAP_CONFIGURE_DEVICE_ADDRESS		0xFE03
#define VS_GAP_DEVICE_DISCOVERY_REQUEST		0xFE04
#define VS_GAP_DEVICE_DISCOVERY_CANCEL	0xFE05
#define VS_GAP_MAKE_DISCOVERABLE	0xFE06
#define VS_GAP_UPDATE_ADVERTISING_DATA	0xFE07
#define VS_GAP_END_DISCOVERABLE		0xFE08
#define VS_GAP_ESTABLISH_LINK_REQUEST	0xFE09
#define VS_GAP_TERMINATE_LINK_REQUEST	0xFE0A
#define VS_GAP_AUTHENTICATE		0xFE0B
#define VS_GAP_PASSKEY_UPDATE	0xFE0C
#define VS_GAP_SLAVE_SECURITY_REQUEST	0xFE0D
#define VS_GAP_SIGNABLE	0xFE0E
#define VS_GAP_BOND 0xFE0F
#define VS_GAP_TERMINATE_AUTH	0xFE10
#define VS_GAP_UPDATE_LINK_PARAMETER_REQUEST	0xFE11
#define VS_GAP_SET_PARAMETER	0xFE30
#define VS_GAP_GET_PARAMETER	0xFE31
#define VS_GAP_RESOLVE_PRIVATE_ADDRESS	0xFE32
#define VS_GAP_SET_ADVERTISEMENT_TOKEN	0xFE33
#define VS_GAP_REMOVE_ADVERTISEMENT_TOKEN	0xFE34
#define VS_GAP_UPDATE_ADVERTISEMENT_TOKENS	0xFE35
#define VS_GAP_BOND_SET_PARAMETER	0xFE36
#define VS_GAP_BOND_GET_PARAMETER	0xFE37
#define VS_UTIL_RESERVED	0xFE80
#define VS_UTIL_NV_READ	0xFE81
#define VS_UTIL_NV_WRITE	0xFE82
#define VS_RESERVED	0xFF00
#define VS_USER_PROFILES	0xFF80

#if 1 /* GATT Command Opcodes */
/* GATT COMMAND OPCODES */
#define GATT_FINDINCLUDEDSERVICES	0xFDB0
#define GATT_DISCALLCHARS	0xFDB2
#define GATT_EXCHANGE_MTU	0XFD82
#define GATT_DISCCHARSBYUUID	0xFD88
#define GATT_DISCALLCHARDESCS	0XFD84
#define GATT_READCHARVALUE	0xFD8A
#define GATT_READUSINGCHARUUID	0xFDB4
#define GATT_READLONGCHARVALUE	0xFD8C
#define GATT_READMULTICHARVALUES	0xFD8E
#define GATT_WRITENORSP		0xFDB6
#define GATT_SIGNEDWRITENORSP	0xFDB8
#define GATT_WRITECHARVALUE	0xFD92
#define GATT_WRITELONGCHARVALUE	0xFD96
#define GATT_READCHARDESC	0xFDBC
#define GATT_READLONGCHARDESC	0xFDBE
#define GATT_WRITECHARDESC	0xFDC0
#define GATT_WRITELONGCHARDESC	0xFDC2
#define GATT_NOTIFICATION	0xFD9B
#define GATT_INDICATION		0xFD9D
#define GATT_ADDSERVICE		0xFDFC
#define GATT_DELSERVICE		0xFDFD
#define GATT_ADDATTRIBUTE	0xFDFE
/* GATT EVENT OPCODES */
#define GATT_CLIENTCHARCFGUPDATED	0x0580
#endif /* GATT Command Opcodes */

#define EVENT_VS_HCI_EXTENSION_SET_RX_GAIN	0x0400
#define EVENT_VS_HCI_EXTENSION_SET_TX_POWER	0x0401
#define EVENT_VS_HCI_EXTENSION_ONE_PACKET_PER_EVENT	0x0402
#define EVENT_VS_HCI_EXTENSION_CLOCK_DIVIDE_ON_HALT	0x0403
#define EVENT_VS_HCI_EXTENSION_DECLARE_NV_USAGE	0x0404
#define EVENT_VS_HCI_EXTENSION_DECRYPT	0x0405
#define EVENT_VS_HCI_EXTENSION_SET_LOCAL_SUPPORTED_FEATURES	0x0406
#define EVENT_VS_HCI_EXTENSION_SET_FAST_TX_RESPONSE_TIME	0x0407
#define EVENT_VS_HCI_EXTENSION_MODEM_TEST_TX	0x0408
#define EVENT_VS_HCI_EXTENSION_MODEM_HOP_TEST_TX	0x0409
#define EVENT_VS_HCI_EXTENSION_MODEM_TEST_RX	0x040A
#define EVENT_VS_HCI_EXTENSION_END_MODEM_TEST		0x040B
#define EVENT_VS_HCI_EXTENSION_SET_BDADDR		0x040C
#define EVENT_VS_HCI_EXTENSION_SET_SCA	0x040D
#define EVENT_VS_HCI_EXTENSION_ENABLE_PTM	 	0x040E
#define EVENT_VS_HCI_EXTENSION_SET_FREQUENCY_TUNING	0x040F
#define EVENT_VS_HCI_EXTENSION_SAVE_FREQUENCY_TUNING	0x0410
#define EVENT_VS_HCI_EXTENSION_SET_MAX_DTM_TX_POWER	0x0411
#define EVENT_VS_HCI_EXTENSION_MAP_PM_IO_PORT		0x0412
#define EVENT_VS_HCI_EXTENSION_DISCONNECT_IMMEDIATE	0x0413
#define EVENT_VS_HCI_EXTENSION_PACKET_ERROR_RATE	0x0414
#define EVENT_VS_HCI_EXTENSION_PACKET_ERROR_RATE_BY_CHANNEL	0x0415
#define EVENT_VS_HCI_EXTENSION_EXTEND_RF_RANGE	0x0416
#define EVENT_VS_HCI_EXTENSION_ADVERTISER_EVENT_NOTICE	0x0417
#define EVENT_VS_HCI_EXTENSION_CONNECTION_EVENT_NOTICE	0x0418
#define EVENT_VS_HCI_EXTENSION_HALT_DURING_RF		0x0419
#define EVENT_VS_HCI_EXTENSION_SET_SLAVE_LATENCY_OVERRIDE		0x041A
#define EVENT_VS_HCI_EXTENSION_BUILD_REVISION		0x041B
#define EVENT_VS_HCI_EXTENSION_DELAY_SLEEP	0x041C
#define EVENT_VS_HCI_EXTENSION_RESET_SYSTEM	0x041D

#define EVENT_VS_HCI_EXTENSION_OVERLAPPED_PROCESSING				0x041E
#define EVENT_VS_HCI_EXTENSION_NUMBER_COMPLETED_PACKETS_LIMIT		0x041F
#define EVENT_VS_HCI_EXTENSION_GET_CONNECTION_INFORMATION		0x0420
#define EVENT_VS_L2CAP_COMMAND_REJECT							0x0481
#define EVENT_VS_L2CAP_CONNECTION_PARAMETER_UPDATE_RESPONSE	0x0493
#define EVENT_VS_L2CAP_CONNECTION_REQUEST			0x0494
#define EVENT_VS_L2CAP_CHANNEL_ESTABLISHED		0x04E0
#define EVENT_VS_L2CAP_CHANNEL_TERMINATED			0x04E1
#define EVENT_VS_L2CAP_OUT_OF_CREDIT				0x04E2
#define EVENT_VS_L2CAP_PEER_CREDIT_THRESHOLD		0x04E3
#define EVENT_VS_L2CAP_SEND_SDU_DONE				0x04E4
#define EVENT_VS_L2CAP_DATA						0x04F0

#define EVENT_VS_ATT_ERROR_RESPONSE				0x0501
#define EVENT_VS_ATT_EXCHANGE_MTU_REQUEST		0x0502
#define EVENT_VS_ATT_EXCHANGE_MTU_RESPONSE		0x0503
#define EVENT_VS_ATT_FIND_INFORMATION_REQUEST	0x0504
#define EVENT_VS_ATT_FIND_INFORMATION_REQUEST	0x0505
#define EVENT_VS_ATT_FIND_BY_TYPE_VALUE_REQUEST	0x0506
#define EVENT_VS_ATT_FIND_BY_TYPE_VALUE_RESPONSE	0x0507
#define EVENT_VS_ATT_READ_BY_TYPE_REQUEST		0x0508

#define EVENT_VS_ATT_READ_REQUEST				0x050A
#define EVENT_VS_ATT_READ_RESPONSE				0x050B
#define EVENT_VS_ATT_READ_BLOB_REQUEST			0x050C
#define EVENT_VS_ATT_READ_BLOB_RESPONSE			0x050D
#define EVENT_VS_ATT_READ_MULTIPLE_REQUEST		0x050E
#define EVENT_VS_ATT_READ_MULTIPLE_RESPONSE		0x050F
#define EVENT_VS_ATT_READ_BY_GROUP_TYPE_REQUEST	0x0510
#define EVENT_VS_ATT_READ_BY_GROUP_TYPE_RESPONSE	0x0511
#define EVENT_VS_ATT_WRITE_REQUEST				0x0512

#define EVENT_VS_ATT_PREPARE_WRITE_REQUEST		0x0516
#define EVENT_VS_ATT_PREPARE_WRITE_RESPONSE		0x0517
#define EVENT_VS_ATT_EXECUTE_WRITE_REQUEST		0x0518
#define EVENT_VS_ATT_EXECUTE_WRITE_RESPONSE		0x0519
#define EVENT_VS_ATT_HANDLE_VALUE_NOTIFICATION	0x051B
#define EVENT_VS_ATT_HANDLE_VALUE_INDICATION		0x051D
#define EVENT_VS_ATT_HANDLE_VALUE_CONFIRMATION	0x051E


#define VS_GAP_DEVICE_INIT_DONE				0x0600
#define VS_GAP_DEVICE_DISCOVERY				0x0601
#define VS_GAP_ADVERT_DATA_UPDATE_DONE		0x0602
#define VS_GAP_MAKE_DISCOVERABLE_DONE		0x0603
#define VS_GAP_END_DISCOVERABLE_DONE		0x0604
#define VS_GAP_LINK_ESTABLISHED				0x0605
#define VS_GAP_LINK_TERMINATED				0x0606
#define VS_GAP_LINK_PARAMETER_UPDATE		0x0607
#define VS_GAP_RANDOM_ADDRESS_CHANGED		0x0608
#define VS_GAP_SIGNATURE_UPDATED			0x0609
#define VS_GAP_AUTHENTICATION_COMPLETE		0x060A
#define VS_GAP_PASSKEY_NEEDED				0x060B
#define VS_GAP_SLAVE_REQUESTED_SECURITY	0x060C
#define VS_GAP_DEVICE_INFORMATION			0x060D
#define VS_GAP_BOND_COMPLETE				0x060E
#define VS_GAP_PAIRING_REQUESTED			0x060F
#define VS_COMMAND_STATUS					0x067F

#define VS_TI_ATT_READ_BY_TYPE_RESPONSE		0x0509
#define VS_GATT_WRITE_CHAR_VALUE			0xFD92
#define VS_GATT_WRITE_NO_RESP				0xFDB6
#define VS_ATT_WRITE_RESPONSE_EVENT		0x0513
#define VS_TI_ATT_EXCHANGE_MTU_RESPONSE	0x0503

